import "./globals.css";

export const metadata = {
   title: "Next.js with app router",
   description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body>
            <header>
               <p>Header</p>
            </header>
            {children}{" "}
            <footer>
               <p>this is the footer.</p>
            </footer>
         </body>
      </html>
   );
}
